---
title: "Reading List: Legal & Business Aspects"
description: Various readings and learnings about business and legal aspects of Open Source intellectual property.
tags: ["reading list"]
categories: "legal"
aliases:
    - /foss/reading-list-legal/
downloadBtn: "true"

---
:toc:

This reading list is a collection of resources on legal and business aspects of open source.
Legal and business aspects of an open source project are part of the foundation for building your project and community.
The resources linked here are intended to give you a better idea of open source from a legal perspective.


[[foundations]]
== Foundations

* https://opensource.org/osd-annotated[The Open Source Definition (Annotated)] - _Open Source Initiative_
* https://opensource.org/licenses/alphabetical[Open Source Licenses by Name] - _Open Source Initiative_
* https://opensource.com/resources/what-is-copyleft[What is copyleft?] - _https://twitter.com/FunnelFiasco[Ben Cotton], Opensource.com_


[[choosing]]
== Choosing a license

* https://choosealicense.com/[Choose an open source license] - _curated by GitHub_
* https://tldrlegal.com/[TLDRLegal - Software licenses explained in plain English] - _FOSSA, Inc_

[[choosing-permissive]]
=== Choosing permissive

You have decided you want to choose a permissive license, but now what?
Unless you have a good reason, there are 3-4 licenses that are most appealing.
These resources will help you figure out key differences between common permissive licenses.

* https://opensource.com/article/18/2/how-make-sense-apache-2-patent-license[How to make sense of the Apache 2 patent license]:
  "The Apache 2 license's patent grant, often misunderstood, makes open source safe to use."
  (https://www.linkedin.com/in/jrkaufman/[_Jeffrey Robert Kaufman_], _Opensource.com_)

[[choosing-copyleft]]
=== Choosing copyleft

You have decided you want to choose a copyleft license, but now what?
These resources will help you figure out the differences between the most common copyleft licenses.

* https://www.quora.com/What-is-the-difference-between-GPL-AGPL-and-LGPL-licenses[What is the difference between GPL, AGPL and LGPL licenses?] - _Quora_
* https://www.gnu.org/licenses/why-affero-gpl.en.html[Why the Affero GPL] - _Free Software Foundation (FSF)_


[[examples]]
== Examples

These are a collection of specific examples or scenarios with Open Source licenses.
They may cover specific projects using a specific license, or may be more general-purpose considerations for any license.

[[examples-software]]
=== Software licenses

* https://web.archive.org/web/20201022120640/https://raymii.org/s/blog/I_enforced_the_AGPL_on_my_code_heres_how_it_went.html[I enforced the AGPL on my code, here's how it went]:
  When enforcing a copyleft license resulted in non-cooperation instead of collaboration.
  While effective at protecting your work, copyleft licenses can be overwhelming to others who do not understand Open Source.
  The practical example in this article is a good reminder of possible outcomes when it comes to enforcing copyleft licenses.

[[examples-content]]
=== Content licenses

* Creative Commons *NonCommercial clause*:
** https://creativecommons.org/faq/#does-my-use-violate-the-noncommercial-clause-of-the-licenses[Does my use violate the Creative Commons NonCommercial clause of the licenses?]:
   Commonly misunderstood, the NonCommercial clause of the Creative Commons licenses are clear in prohibiting uses that are “primarily intended for or directed toward commercial advantage or monetary compensation.”
   This F.A.Q. by the Creative Commons offers more details on what NonCommercial implies.
** https://wiki.creativecommons.org/wiki/NonCommercial_interpretation[NonCommercial interpretation]:
   The NonCommercial license element, explained.
   If you want the deep dive on everything about Creative Commons NonCommercial licenses, this is it.

[[examples-data]]
=== Data licenses

These are examples of licenses or projects with open data licenses.

* https://www.openstreetmap.org/copyright[OpenStreetMap - Copyright and License] - _OpenStreetMap_
** Good example of a project with an open data license
* Open Data Commons Open Database License (ODbL)
** https://opendatacommons.org/licenses/odbl/[Overview]
** https://opendatacommons.org/licenses/odbl/summary/[Human-readable summary]
