---
title: "Templates for programme mentors"
description: Various templates and reusable copytext for UNICEF Open Source Mentorship programme mentors.
tags: ["tools"]
categories: "meta"
aliases:
    - /meta/templates/
downloadBtn: "true"

---
:toc:

This page is a copy-paste template of various templates I use for Open Source Mentorship meetings.
I use these for my private notes about each team's progress.


== Induction agenda template

* *Agenda*:
** Introductions
** Offer to record call
** Review O.S. Terms of Reference
** Review frequently-used resources (i.e. UNICEF Open Source Inventory & evaluation rubric)
** link:++{{< relref "needs-assessment-template" >}}++[Needs assessment] (Q&A)
** Open source strategy (12-month vision, 1-month action plan)
* *Needs assessment*:
* *Open source strategy*:
* *Action items for next time*:


== Initial research template

A template to help me prepare for Open Source induction calls.
I have to get to know who I am talking to!

* *Tech stack*:
* *Elevator pitch*:
* *Expected Results*:
* *Quarter-by-quarter breakdowns*:
** _Q1_:
** _Q2_:
** _Q3_:
** _Q4_:
* *Revenue streams*:
* *Collaborations*:
* *Open Source*:
** _Current_ (if any):
** _Future_:
* *Team*:
* *Repository Overview*:
* *Initial thoughts / recommendations*:


== Email summary template

Coming soon.
