---
title: "How to create a new Inventory Mission"
weight: 14
description: Guidance on creating a new Mission in the Open Source Inventory.
tags: ["content"]
categories: "meta"

---
:toc:

This how-to article explains how to create a new category in the Open Source Inventory.
This how-to article explains how to create a new link:++{{< ref "missions" >}}>++[Mission] in the Open Source Inventory.


[#steps]
== Steps

. Copy the Mission template as a new file using the file committed at `content/meta/_template.en.adoc`.
. Edit the template front-matter to include a `weight`, `description`, `tags`, and `categories`
  (see descriptions below).
. Edit the content using the questions in the template as structural guidelines.
. Remove `draft: true` from the front-matter.
. Publish changes and submit a Pull Request.


[[front-matter]]
== Front-matter data values

All Missions (and all content on the site) should specify the following required metadata:

[source,yaml]
----
title: Build a rocketship <1>
weight: 10 <2>
description: Embark on a new mission to build your first rocketship to Mars. <3>
tags: ["design", "hardware", "teamwork"] <4>
categories: "missions" <5>
----
<1> `title` is a noun in plural form. It clearly defines what the Mission topic is.
<2> `weight` is set to maintain alphabetical sort order on all Missions. Check other Missions first to find the right value.
<3> `description` is one, at most two, sentences to describe the Mission topic.
<4> `tags` is a descriptive list of words to describe key elements of the Mission. Check other Missions to see tags already in use.
<5> `categories` is a single value and must always be set to `missions` for a new Mission.
