---
title: "Modules"
weight: 10

---
// document settings
:toc:
:hide-uri-scheme:

The UNICEF Open Source Mentorship programme offers multiple learning modules and mentorship topics.
This page provides an overview of the different modules currently offered through the Open Source Mentorship programme.

. link:#offered[Offered modules]
.. link:#offered-legal[Legal & Licensing: Foundations of Open Source intellectual property]
.. link:#offered-launching[Launching your Open Source project]
.. link:#offered-docs[Open Source documentation]
.. link:#offered-ci[Continuous Integration for continuous contribution]
.. link:#offered-archetypes[Archetypes: Shape and size of Open Source over time]


[[offered]]
== Offered modules

The following modules are currently offered in UNICEF-facilitated mentorship:

[[offered-legal]]
=== Legal & Licensing: Foundations of Open Source intellectual property

____
Building an Open Source community is like building a house.
A good house must have a solid foundation, and Open Source projects are no different.
The licenses surrounding Open Source, sometimes called Free Software, are part of the foundation of your Open Source project.
This module introduces the Open Source Definition, the types of Open Source licenses, and how to be strategic and intentional in your choice of licenses.

The Open Source licenses are the legal foundation of your project.
By the end of this module, you should understand how the limits and bounds of your Open Source license impact the rules of your business model.
____

*Topics included*:

* Contributor License Agreements (CLAs)
* Licenses
  (MIT License, Apache License, GPL licenses, etc.)
** Copyleft licenses
** Permissive licenses
* Open Source business models
* Open Source Definition
* Open Source Initiative

[[offered-launching]]
=== Launching your Open Source project

____
Lift-off!
You know your licensing strategy and you are ready to go Open Source.
Now what?
This module introduces Open Source forges and collaboration platforms.
You will learn how to use these tools effectively and efficiently, as well as ways to structure your project in order to scale with a community over time.

This module is for early-stage Open Source projects that are still in active development.
By the end of this module, you should understand common Open Source development workflows and how to enable collaboration with advanced features of your source code-hosting platform.
____

*Topics included*:

* Brand and identity
* Git platforms:
  GitHub, GitLab, Bitbucket, Pagure, etc.
* Pull Request workflow
* READMEs
* Using issues to manage product feedback

[[offered-docs]]
=== Open Source documentation

____
If everyone knew a programming language, source code alone might be enough.
But most people do not know a programming language, and some people who use your project will not be engineers or developers with specialized knowledge.
Planning, creating, and maintaining Open Source documentation fills an unavoidable gap to improve accessibility and understanding of your Open Source project.
This module introduces the following:

* Common tools and platforms used for Open Source documentation;
* How to build an automated pipeline to deploy new documentation in real-time;
* Building a documentation culture and community in your project;
* Creating structure to enable external contributions to documentation.

By the end of this module, your project will have an Open Source documentation site and a plan on how to maintain the documentation over time.
This module is for any Open Source project, at any stage, that wants to improve their documentation acumen and invite others to collaborate and contribute.
____

*Topics included*:

* Automation tools
  (e.g. GitHub Actions, Circle CI, etc.)
* Contribution guidelines
* Documentation for developers
* Documentation for users
* Tool-chains
** Python Sphinx
** Hugo
** Docusaurus
   (Facebook)


[[offered-ci]]
=== Continuous Integration for continuous contribution

[[offered-archetypes]]
=== Archetypes: Shape and size of Open Source over time


== Module programming

The above modules are typically offered in groups with other modules.
The programmes and most common combination of modules are described below:

=== 12-month Innovation Fund contracts

[[roadmap-q1]]
==== Q1

[[roadmap-q2]]
==== Q2

[[roadmap-q3]]
==== Q3

[[roadmap-q4]]
==== Q4

=== 3-month Office of Innovation support engagement

==== Month 1

==== Month 2

==== Month 3


== Modules in progress

The following is a list of modules currently in progress:
