---
title: Introduction to Open Source Hardware
weight: 1
description: So, you want to know about Open Source Hardware? Start here to get an introduction to the landscape in the 2020s.
tags: ["philosophy"]
categories: "hardware"
downloadBtn: "true"

---
:definition: https://www.oshwa.org/definition/
:toc:

So… you want to know about Open Source Hardware?
This page is an introduction to what Open Source Hardware means, how it works, and why it matters.
Other pages in this Open Source Heuristic category will expand your understanding of Open Source Hardware;
however, if you need a place to begin, this is a good start!


[[overview]]
== What is Open Source Hardware?

Open Source Hardware, sometimes abbreviated as O.S.H.W., is sometimes used as a general term to describe hardware projects developed in an open way.
However, the link:#oshwa[Open Source Hardware Association] maintains a {definition}[common definition] of Open Source Hardware, as agreed upon by several stakeholders and contributors to Open Hardware projects.

[quote,Open Source Hardware Association]
____
Open source hardware is hardware whose design is made publicly available so that anyone can study, modify, distribute, make, and sell the design or hardware based on that design.
____

Just like https://opensource.org/osd-annotated[Open Source software], the key definition of Open Hardware includes the https://fsfe.org/freesoftware/[Four Freedoms] to use, study, share, and improve.
The Open Source Hardware Definition provides a common language, standard, and legal framework for Open Source Hardware projects.
Using Open Source Hardware developed according to this definition reduces legal and compliance risk for these kinds of projects.

The Open Source Hardware Association also provides a clear idea of what they mean by "hardware" in the definition:

[quote,Open Source Hardware Association]
____
Open Source Hardware (OSHW) is a term for tangible artifacts — machines, devices, or other physical things — whose design has been released to the public in such a way that anyone can make, modify, distribute, and use those things.
This definition is intended to help provide guidelines for the development and evaluation of licenses for Open Source Hardware.
Hardware is different from software in that physical resources must always be committed for the creation of physical goods.
Accordingly, persons or companies producing items (“products”) under an OSHW license have an obligation to make it clear that such products are not manufactured, sold, warrantied, or otherwise sanctioned by the original designer and also not to make use of any trademarks owned by the original designer.
____

[[overview-takeaway]]
=== Takeaway

So, the main idea or point to understand about Open Source Hardware?
Whenever we talk about Open Source Hardware projects, we need to make sure we are using common language.
Open Source Hardware does not prohibit or forbid commercialization, but it does offer protections for unique trademarks and responsibilities from liability.
When an Open Source Hardware project is released, we always promise end-users four rights.
You can remember them as the *Four R's*:

. *Read*:
  Anyone can read the specs and see how the hardware is designed and built.
  There are instructions provided about how to do so.
. *Reproduce*:
  Anyone can make their own hardware using the specs.
  There are no absolute restrictions on how the hardware must be used.
. *Revise*:
  Anyone can make changes to the specs in any way they wish.
. *Redistribute*:
  Anyone can share their changes to the specs with others.


[[examples]]
== Where does Open Source Hardware exist today?

This site provides several examples of popular Open Source Hardware projects.
Look at the link:++{{< relref "projects" >}}++[Project Hall of Fame] for many different examples.
Review the link:++{{< relref "case-studies" >}}++[Case studies] for detailed explanations about different Open Source Hardware projects and businesses.


[[benefits]]
== Why Open Source Hardware is a win for your project

The Open Source Hardware option is a competitive strategy for a new product or creation, if planned correctly.
Choosing to work Open Source allows to be more successful in collaboration and creating new partnerships.
Its focus on reproduction and standardization across borders makes it a competitive option for deploying new hardware with potential to scale.

However, there are a few distinct, key reasons why an Open Source Hardware route is a win for your next product.
This list is not exhaustive and focuses more narrowly on the start-up perspective:

[[benefits-reproducibility]]
=== Reason no. 1: Reproducibility

Open Source Hardware should be reproducible.
Generally, this means using commonly-available components and standardized conventions.
It also requires reliable documentation on reproduction of the hardware itself.
By generalizing where possible and providing useful documentation, it empowers others to reproduce the same device in a different geographical context or market.

Successful Open Source Hardware projects take reproducibility to heart.
It is a defining characteristic of those projects, although they may sometimes be a smaller component in a larger proprietary hardware project.
By leveraging reproducibility to the fullest, it will best prepare you for the next major benefit of Open Source Hardware projects.

[[benefits-community]]
=== Reason no. 2: Community participation

Open Source Hardware projects can benefit by leveraging feedback loops by communities of makers and modders from around the world.
The participation of diverse contributors allows you to create strategic new partnerships and create innovative work more quickly.
However, you only stand to benefit from this community participation if you have both a clearly reproducible project, and an active approach to community management and growing a healthy community around the project.

[[benefits-trademark]]
=== Reason no. 3: Trademark protections

Finally, Open Source Hardware projects also benefit from trademark protection.
Even though you release your hardware schematics and documentation as Open Source, this does not allow the general public to use marks that may confuse your organization with changes made to the software by others in the ecosystem.
Trademarks often seem trivial or unimportant in the beginning of an Open Source project.
However, if the project will scale, the trademarks of the primary owner of a project need to be clearly defined to clearly distinguish the original project from any community forks.

Are you starting a new project?
If you are starting fresh, you have room for creativity.
Think about how to market or promote your project through its name or a logo.
For projects intended for wider public participation, spend the time early to build the brand of the project and clearly identify any marks.
This will become useful in the future to support a product brand and a community brand.


[[oshwa]]
== Open Source Hardware Association

Open Source Hardware is {definition}[defined] by the https://www.oshwa.org/about/[Open Source Hardware Association] (O.S.H.W.A.).
O.S.H.W.A. provides a https://certification.oshwa.org/[certification process] for producers to indicate their products meet a uniform and well-defined standard.
Certification is a valuable milestone for any product considering to release as Open Source Hardware.
It builds trust and transparency into how you market and promote your product as genuine Open Source Hardware.

For more questions about O.S.H.W.A. certification, see their https://certification.oshwa.org/basics/faq.html[Frequently Asked Questions page].


[[resources]]
== Resources and other references

* https://opensource.com/resources/what-open-hardware[What is Open Hardware?] (_opensource.com_)
