---
title: Licensing
description: Information, resources, and details about common licenses used for Open Source Hardware projects.
tags: ["legal"]
categories: "hardware"
downloadBtn: "true"

---
:toc:

This page collects information, resources, and other details about Open Hardware licensing.


== Documentation

* https://openhardware4.me/open-hardware-leaders.github.io/Program/17_Week10.html[Licensing and documentation]:
  Learning material provided by Open Hardware Leaders program.
  Goal of material is to acquire best practices for hardware documentation and understand the different open licensing options available.
  Includes an explanation video and other helpful links.


== Licenses

There are two generally accepted Open Hardware licenses:

* https://ohwr.org/cernohl[CERN Open Hardware Licence]
* https://tapr.org/the-tapr-open-hardware-license/[TAPR Open Hardware License]

Each can come with its own strategy.
For example, the https://home.cern/news/news/knowledge-sharing/cern-updates-its-open-hardware-licence[2.0 version of the CERN open hardware license] includes three versions:

* "Weakly" reciprocal
* "Strongly" reciprocal
* Non-reciprocal

A reciprocal license is similar to https://opensource.com/resources/what-is-copyleft[copyleft] for software licenses, meaning others who make use of your work must share their derivatives under the same license.
This way, no one can take what you made, make changes, and turn it into a closed-source product.
You will benefit from others’ contributions, especially if you build a community around your product.

=== https://linuxfestnorthwest.org/conferences/lfnw18/program/proposals/72[Don’t Fear the Patent Clause!]

A talk from Deb Nicholson at LinuxFest Northwest 2018:

[quote,Deb Nicholson]
____
Several different patent clauses are embedded in modern open source licenses and there’s some confusion about exactly what they each mean.
Most developers would prefer to have nothing to do with patents or patent clauses, but avoiding the topic isn’t a smart strategy.
None of the popular clauses have been tested in court, so no one can predict exactly how the courts might deal with hybrid copyright and patent licenses.

That said, savvy open source participants can still make some reasonable assumptions based on the license author’s intentions, trends in patent law and the way other common open source licenses have functioned.
Understanding the players and the history that lead to patent clauses in open source licenses will help practitioners make informed choices about what licenses to apply to their own work and how these various licenses can help large multi-stakeholder projects.
____

{{< youtube LqMdaKE8zkI >}}
