---
title: Project Hall of Fame
description: Various Open Source Hardware projects and links back to their projects and/or communities.
tags: ["hall of fame"]
categories: "hardware"
downloadBtn: "true"

---

This page collects various Open Hardware projects.
These projects are not officially endorsed, but are listed here as a convenience to generate a list of examples for reference.
For more detailed overviews, see the link:{{< relref "case-studies" >}}[Case Studies] page.

Check out the list of https://certification.oshwa.org/list.html[certified hardware] from the Open Source Hardware Association for more inspiration.


== Businesses & companies

* https://www.adafruit.com/[*Adafruit Industries*]
* *Aleph Objects*:
  Makers of https://www.lulzbot.com/about[LulzBot] family of 3D printers.
  Purchased by Fargo Additive Manufacturing Equipment 3D in 2019.
* https://www.arduino.cc/en/Main/FAQ[*Arduino*]:
  Open-source electronics platform based on easy-to-use hardware and software.
* https://farm.bot/[*FarmBot*]
* https://iorodeo.com/pages/about-us[*IO Rodeo*]
* https://www.prusa3d.com/[*Prusa Research*]:
  Manufactures 3D printers for enterprise and hobbyists.
* https://www.seeedstudio.com/[*Seeed Studio*]
* https://ultimaker.com/about-ultimaker[*Ultimaker*]
* *World Famous Electronics*:
  Maker of the https://pulsesensor.com/[Pulse Sensor].
  Never applied for funding beyond initial crowdfunding campaign.

=== Emergency response

* https://safecast.org/about/[*Safecast*]:
  International, volunteer-driven, non-profit organization.
  Goal is to create useful, accessible, and granular environmental data.

=== Neuroscience

Organizations with a specific focus to neuroscience.

* https://backyardbrains.com/about/[*Backyard Brains*]
* https://openbci.com/[*OpenBCI*]
* https://open-ephys.org/[*Open Ephys*]
* https://sanworks.io/[*Sanworks*]


== Distributors

* https://www.olimex.com/[*OLIMEX*]
* https://www.sparkfun.com/[*Sparkfun*]


== Specific products & projects

* https://www.crowdsupply.com/[*Crowd Supply*]:
  Popular platform for Open Hardware crowdfunding.
  Not all funded projects are open source, but many are.
* https://github.com/OpenROV[*OpenROV*]:
  Low-cost telerobotic submarine/underwater drone built with the goal of making underwater exploration and education affordable (see https://en.wikipedia.org/wiki/OpenROV[Wikipedia]).
* https://riscv.org/risc-v-history/[*RISC-V*]
