---
title: "Open Hardware reading list"
description: Various readings and learnings about Open Source Hardware that do not belong on another page.
tags: ["reading list"]
categories: "hardware"
downloadBtn: "true"

---

A collection of various readings and articles related to Open Hardware.


== Innovation

* https://hbr.org/2021/06/how-low-and-middle-income-countries-are-innovating-to-combat-covid[*How Low and Middle-Income Countries Are Innovating to Combat Covid*], _HBR.org_:
  "One-fifth of the innovative solutions to fight the Covid-19 pandemic have emerged from low and middle-income countries, and these responses offer promising insights for how we think about, manage, and enable innovation.
  As the international community now faces the historic challenge of vaccinating the world, more attention and resources must be directed to the innovators who are developing technically novel, contextually relevant, and socially inclusive alternatives to mainstream innovation management practices."

[quote, hbr.org, Published 9 June 2021 - copyright Harvard Business Review and shared under Fair Use or §107 Copyright Law of the United States (Title 17)]
____
For example, innovators in low- and middle-income countries have developed numerous solutions that rely almost entirely on off-the-shelf parts that can be found in hardware stores.
One example that quickly reached the Indian market is the AgVa portable ventilator, which:

* Doesn’t need an oxygen supply
  (it oxygenates room air)
* Builds on the computational power of mobile phones and a dedicated app
* Weighs a fraction of typical commercial ventilators, making it easily portable
* Has open-source specifications, making it adaptable for use in other countries and contexts
* Costs less than a tenth of conventional ventilators and can be produced much more quickly.
____


== Legal and Business Aspects

* https://openhardware.metajnl.com/articles/10.5334/joh.4/[Emerging Business Models for Open Source Hardware]:
  Many ideas on open hardware business models.
  Focuses more narrowly for science use cases, but still a helpful perspective.
* https://mitpress.mit.edu/books/free-innovation[Free Innovation], _Eric von Hippel_
* https://forum.openhardware.science/t/why-public-institutions-should-release-more-of-their-hardware-designs-as-open-source-hardware/2235[Why public institutions should release more of their hardware designs as Open-Source Hardware]:
  Opinion article from the open hardware initiator at CERN, Javier Serrano.
  Gives a general and broad overview of today's environment.


== Science

* https://www.preprints.org/manuscript/202003.0362/v1[Leveraging Open Hardware to Alleviate the Burden of COVID-19 on Global Health Systems]:
  March 2020 publication on the role of Open Hardware in addressing various shortcomings in the medical community's response to COVID-19.
  Explains role of Free and Open Source Hardware (F.O.S.H.) developed and deployed in the scientific and medical communities to enable greater access to life-saving resources and tools.
* https://www.sciencedirect.com/science/article/pii/S2212827118312095[Measuring Openness in Open Source Hardware with the Open-o-Meter]:
  2018 research on Open Hardware and building a common language of what Open Hardware is and how something is determined as "open" or not.
  Presents a marking scheme that allows rating the openness of a product.


== Miscellaneous

Anything that is unique from any other sections.

* https://github.com/Open-Hardware-Leaders/Resources[Collaborative list of Open Hardware resources]:
  "Awesome"-style, curated articles, websites, and resources by the Mozilla Open Hardware Leaders cohort.
  Features even more readings organized by different topics.
* https://www.zotero.org/groups/2312397/open_hardware/library[Zotero reference group]:
  References and citations for Open Hardware works.
  Note this is likely most helpful for academics and researchers.
