---
title: Documentation Hall of Fame
description: Real examples of Open Source projects with excellent documentation.
tags: ["hall of fame"]
categories: "documentation"
downloadBtn: "true"

---
:toc:

This page is a collection of good examples of Open Source documentation projects.
The projects and examples listed here are not endorsements.
It is a collection of good examples to inspire your own Open Source documentation!


[[aggregations]]
== Aggregations

The projects listed below aggregate several existing documentation projects:

* https://github.com/vipulgupta2048/awesome-documentation[*Awesome Documentation*]:
  Community-curated resource with examples of great documentation in Open Source projects.
* https://github.com/derberg/awesome-docs-with-static-site-generators[*Awesome Docs with Static Site Generators*]:
  This repo is suppose to give you a bunch of links to themes or ready implementations of documentation portals.
  They will help you to quickly get some good samples to play with a static site generator that you are interested with.
* https://project-awesome.org/matiassingers/awesome-readme[*Awesome READMEs*]:
  A curated list of awesome READMEs.
  Find the source content https://github.com/matiassingers/awesome-readme[on GitHub].


[[dev-docs]]
== Developer documentation

These examples show projects that offer clear and concise documentation for developers:

* *Small project*:
  https://docs.teleirc.com/[TeleIRC]
** Small project with over 20 contributors and over five years of activity.
** Developer docs are focused on explaining key topics that come up often with new contributors:
*** Coding conventions by project maintainers
*** Contributing guidelines
*** Architecture/state diagram
*** Code testing best practices

* *Medium to large projects*:
** https://docs.mongodb.com/manual/[MongoDB]
** https://laravel.com/docs/[Laravel]
** https://google.github.io/mediapipe/[*Google MediaPipe*]:
   MediaPipe offers cross-platform, customizable ML solutions for live and streaming media.
   MediaPipe documentation clearly explains what MediaPipe is, its strongest benefits as a tool for developers, and helpful information to start using it.

* *Large project*:
  https://jupyterlab.readthedocs.io/en/latest/developer/repo.html[JupyterLab]
** JupyterLab is a large project with over 300 contributors and used by nearly 30,000 GitHub users.
** Extensive and well-organized developer documentation on a range of topics.
   Not only coding.


[[toolchains]]
== Toolchain-specific examples

These examples are aggregated by specific toolchains commonly used for Open Source documentation.

[[hugo]]
=== Golang Hugo

These examples are good examples of documentation written using the https://gohugo.io/[Hugo] documentation tool-chain.

* https://github.com/unicef/inventory[*UNICEF Open Source Inventory*]:
  This website you are reading right now?
  The content is written in a mix of AsciiDoc and Markdown, and published with Hugo.

[[sphinx]]
=== Python Sphinx

These examples are good examples of documentation written using the https://www.sphinx-doc.org/[Python Sphinx] documentation tool-chain.
Sphinx has integrations that simplify writing API documentation for Python projects, based on code comments in doc-strings.

* https://github.com/jwflory/sphinx-docs-opinionated-quickstart[*sphinx-docs-opinionated-quickstart*]:
  Quick-start, opinionated template repository to add Sphinx-based documentation to an existing project.
  Includes ready-to-use https://travis-ci.com/github/jwflory/sphinx-docs-opinionated-quickstart[Travis CI] and https://sphinx-docs-opinionated-quickstart.readthedocs.io/[ReadTheDocs.org] configuration files, so you can start writing your docs, and spend less time figuring out tools.
* https://parsy.readthedocs.io/[*parsy*]:
  Parsy is an easy way to combine simple, small parsers into complex, larger parsers.
  If it means anything to you, it's a monadic parser combinator library for LL(infinity) grammars in the spirit of https://github.com/haskell/parsec[Parsec], http://parsnip-parser.sourceforge.net/[Parsnip], and https://github.com/jneen/parsimmon[Parsimmon].
