---
title: "AI Ethics & Transparency Roadmap - Template"
description: How do you document your machine learning development process? This guide shares transparency best practices.
tags: ["template"]
categories: "data"
downloadBtn: "true"

---

This is your at a glance version of the document.
Details and resources are below.

. Milestone 1: link:#data-flow[*Understanding the Data Flow*]
.. Data Ecosystem Map
.. Information Sharing Protocol
. Milestone 2: link:#understand-algo[*Understanding the Algorithm*]
.. Dataset Structure
.. Common Traps Mitigations
. Milestone 3: link:#document-algo[*Sharing the Model*]
.. Model Card Created


[[data-flow]]
== Understanding Data Flow

* *Primary Goal*:
  Create documentation that ensures you know what data you're using and how you plan on sharing it.

This first milestone is about initially understanding the underlying data powering your model.
This is generally important for understanding the plumbing and getting an idea about privacy and implications that may arise from sharing data.

[[data-flow--outcomes]]
=== Outcomes

* https://docs.google.com/document/d/18Zg2JwUDJajVDX5VU0vMijL-c9yfumeAUYDc7rgC4iQ/edit#[*Data Ecosystem Map*]:
  This is to document where their data is coming from, what’s using it, stakeholders, etc.
  The benefit here is not just helping organize how data collection will work in production but also projecting partnerships which may need to be formed in the future.
* https://docs.google.com/document/d/1MISHbWU7KGo4Z4AR-b222f6uXrtpQ-GJiJemGYoL--E/edit#[*Information Sharing Protocol*]:
  This document is all about conducting an initial assessment of the sensitivity of information you are collecting, who you want to share it with, and how.
  It is fairly well-thought but is worth a review and potentially some edits.
  If you are in the EU, it might just be better to do a https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/data-protection-impact-assessments-dpias/what-is-a-dpia/[Data Protection Impact Assessment].


[[understand-algo]]
== Understanding the Algorithm

* *Primary Goal*:
  Create documentation to ensure your whole team understand exactly how your model will be working.

A large part of this will be determining the method of managing your datasets as they evolve over the development of the program.

[[understand-algo--outcomes]]
=== Outcomes

* https://humanitarian.atlassian.net/wiki/spaces/imtoolbox/pages/61734950/File+and+Dataset+Management[*Determine Dataset Structure*]:
  As you create new data sets, update them, and remove old datasets, you should follow an easy to follow protocol for keeping track of your various data sets as they are updated and deprecated.
* link:++{{< relref "traps" >}}++[*Common Traps When Building Models*]:
  Review the following traps and document potential risks of your application falling into any of these traps.


[[document-algo]]
== Documenting the Algorithm

* *Primary Goal*:
  Produce documentation that should be shared with the model.

[[document-algo--outcomes]]
=== Outcomes

* link:++{{< relref "model-card" >}}++[*Document Machine Learning Model Card*]:
  Before you release or begin production use of your machine learning model, you can use the linked template to comprehensively document the effects, background, and purpose of your model.
  This will serve as a core document showing how the model makes the decision it does.
