---
title: Policy guidance on AI for children (via unicef.org)
description: Recommendations for building AI policies and systems that uphold child rights. Part of UNICEF AI for children project.
tags: ["artificial-intelligence","children", "policy"]
categories: "data"

---

As part of our https://www.unicef.org/globalinsight/featured-projects/ai-children[AI for children project], UNICEF has developed this policy guidance to promote children's rights in government and private sector AI policies and practices, and to raise awareness of how AI systems can uphold or undermine these rights.
The policy guidance explores AI systems, and considers the ways in which they impact children.

[[url]]
== Read in full: https://www.unicef.org/globalinsight/reports/policy-guidance-ai-children[*unicef.org/globalinsight/reports/policy-guidance-ai-children*]

Drawing on the Convention on the Rights of the Child, the guidance offers nine requirements for child-centered AI:

. Support children’s development and well-being
. Ensure inclusion of and for children
. Prioritize fairness and non-discrimination for children
. Protect children’s data and privacy
. Ensure safety for children
. Provide transparency, explainability, and accountability for children
. Empower governments and businesses with knowledge of AI and children’s rights
. Prepare children for present and future developments in AI
. Create an enabling environment

To support implementation of the guidance, a list of online resources and a set of practical implementation tools are provided, including:

. https://www.unicef.org/globalinsight/media/1166/file/UNICEF-Global-Insight-tools-to-operationalize-AI-policy-guidance-2020.pdf[Roadmap for policymakers]
. https://www.unicef.org/globalinsight/media/1166/file/UNICEF-Global-Insight-tools-to-operationalize-AI-policy-guidance-2020.pdf[AI for children development canvas]
. https://www.unicef.org/globalinsight/media/2336/file[AI guide for parents]
. https://www.unicef.org/globalinsight/media/2341/file[AI guide for teens]

To see how the guidance has been applied in practice, read about the eight https://www.unicef.org/globalinsight/policy-guidance-ai-children-pilot-testing-and-case-studies[case studies].

https://www.unicef.org/globalinsight/reports/policy-guidance-ai-children[*_Read more on unicef.org_*].
