---
title: Governance
description: Best practices and examples of governance in real Open Source projects.
tags: ["policy"]
categories: "governance"
aliases:
    - /foss/governance/
downloadBtn: "true"

---
:toc:

This page defines and provides examples of Open Source governance.
This includes Open Source project governance models, examples of other projects, frameworks for decision-making, and more.

This page is a work-in-progress.
Check back later for future additions.


[[about]]
== What is Open Source governance?

The phrase "Open Source governance" generally refers to the decision-making model or documented process for how an Open Source project makes decisions.
Sustainable governance is essential if an Open Source project will last, especially if it involves multiple stakeholders and collaborators.
But what governance models or frameworks are sustainable?
What makes sense for your Open Source project?
The answer is, it depends.

Documenting and defining a governance model for a project is a radical act of transparency.
It is an advance commitment to deciding how decisions are made, who gets to have a say, and how community feedback is factored into the process.
Sometimes governance models need to be changed in the future; this is normal.
A good governance model captures the core values and beliefs of the project, and gives key stakeholders a voice in the future of the project.
It also includes a process to adapt or change, to accommodate unexpected changes in society and norms over time.

This page serves as a reference point for you to determine a governance model for your Open Source project.
Although models and examples are included below, do not take them as an absolute truth.
There is room for creativity and adaption; the right governance model for your project might be a combination of the models explained here.

[[models]]
== Models

This section is deferred.
A list of examples or generic examples will be added later.
For now, check out https://www.redhat.com/en/blog/understanding-open-source-governance-models[this Red Hat blog post] for several models based on real Open Source projects.


[[examples]]
== Examples

Examples and explanations of governance models in popular, well-known Open Source projects.

[[examples-linux]]
=== Linux kernel

_Coming soon_.

[[examples-fedora]]
=== Fedora Project

What is Fedora?

[quote,Fedora Project documentation,https://docs.fedoraproject.org/en-US/project/]
____
The Fedora Project is a community of people working together to build a free and open source software platform and to collaborate on and share user-focused solutions built on that platform.
Or, in plain English, we make an operating system and we make it easy for you do useful stuff with it.

The Fedora community includes thousands of individuals with different views and approaches, but together we share some common values.
We call these the “Four Foundations”:
Freedom, Friends, Features, and First.
____

The https://docs.fedoraproject.org/en-US/council/[Fedora Council] is our overall leadership and governance body.
Most of the project is then roughly organized under https://docs.fedoraproject.org/en-US/fesco/[FESCo] (the Fedora Engineering Steering Committee) or the https://docs.fedoraproject.org/en-US/mindshare-committee/[Mindshare Committee].


[[resources]]
== Resources

This section includes various resources and readings for you to continue your self-education about Open Source governance.

[[resources-exploratory]]
=== Exploratory

Links and resources to tools that will help you explore and learn more about governance.

* https://sustainers.github.io/governance-readiness/[*Governance Readiness Checklist*]:
  A light-weight framework to define the governance model in your software project.
  It is hard to know where to begin if you do not know the questions to ask.
  This quick checklist, created by the Sustain O.S.S. Governance Working Group, includes key questions and considerations for crafting a governance model for your Open Source project.
* https://fossgovernance.org/getting-started[*FOSS Governance Collection*]:
  Comprehensive library of governance models used by real Open Source projects, foundations, non-profits, and more.
  Especially useful if you are looking for examples or inspiration to follow.
* https://discourse.sustainoss.org/t/governance-readiness-working-group/298?u=jwf[*Sustain O.S.S. Governance Working Group*]:
  A volunteer-driven Working Group of people interested in the governance of Open Source projects.
  This is a great place to ask questions and engage with a wider community of professionals about Open Source governance and best practices.
* https://opensource.guide/leadership-and-governance/[*Leadership and Governance*]:
  Growing open source projects can benefit from formal rules for making decisions.
  This guide from GitHub helps you understand governance for your growing project.
  [_opensource.guide_]

[[resources-journalism]]
=== Journalism

Articles and blog posts about Open Source governance.

* https://www.infoworld.com/article/3451796/3-models-for-open-source-governance.html[*3 models for open source governance*]:
  How to balance makers and takers to scale and sustain open source projects, companies, and ecosystems
  (part 4).
  [_infoworld.com_]
* https://opensource.com/article/20/5/open-source-governance[*What is open source project governance?*]:
  Clearly defining roles and responsibilities is essential to effective open source community management.
  Here are some ways to help you organize.
  [_opensource.com_]
* https://www.redhat.com/en/blog/understanding-open-source-governance-models[*Understanding open source governance models*]:
  Open source projects usually operate according to rules, customs, and processes that determine which contributors have the authority to perform certain tasks.
  Understanding those rules can increase your chances of contributing successfully and positively to a project.
  This article provides six examples of common frameworks used for Open Source governance.
  [_redhat.com_]
