---
title: "Reading list: FOSS"
description: Various readings and learnings about Free and Open Source Software.
tags: ["reading list"]
categories: "governance"
aliases:
    - /foss/reading-list-foss/
downloadBtn: "true"

---
:toc:

Readings on a variety of topics about Free & Open Source Software.


[[foundations]]
== Foundations

* https://fsfe.org/freesoftware/[*Four Freedoms of Free Software*]:
  Before understanding anything else about Open Source, you must first understand the core foundation of what decades of Open Source development built upon:
  the Four Freedoms.
  The Four Freedoms can be remembered as the freedoms to _Read, Run, Revise, & Redistribute_.
  This article from Free Software Foundation Europe explains more about the essential four freedoms guaranteed by all users of Open Source technology.


[[governance]]
== Governance

* https://www.cambridge.org/core/services/aop-cambridge-core/content/view/D1341B4E550B8F42032585694B6DB8D8/S205347011800015Xa.pdf/how_participative_is_open_source_hardware_insights_from_online_repository_mining.pdf[*How participative is open source hardware? Insights from online repository mining*]:
  Interesting study of how people work together.
  Or, how governance works even if it is not explicitly designed.
  Notable as an early intersectional conversation on governance models in open hardware communities.
