---
title: Case studies
description: Detailed case studies and analysis of different Open Hardware organizations, projects, and products.
tags: ["hall of fame"]
categories: "hardware"
downloadBtn: "true"

---
:toc:

Below are more detailed case studios of different Open Hardware organizations, projects, and products.
Unlike the link:{{<relref "projects" >}}[Projects] page, these examples are more detailed and provide more context.

== https://opentrons.com/[Opentrons]

Scientific-focused hardware.

[quote,Pen-Yuan Hsing]
____
Several highly successful and well-regarded biology/chemistry lab automation robots.
By going 100% open source, they substantially reduced costs.
Their products’ prices sometimes undercuts competition by 10x.
They also acquired venture capital (V.C.) funding.

Having worked in biology labs myself, I can attest to how revolutionary their open source business model is.
It doesn’t just save cost.
Since everything is open source, scientists who use their products avoid vendor lock-in and some even create their own modifications.
This is shared with other scientists and builds a stronger ecosystem around Opentrons.
____


== Arduino

[quote,Pen-Yuan Hsing]
____
This is probably the most famous example.
The official Arduino boards are 100% open source.
By being fully open source, this allow Arduino boards a significant amount of free publicity.
User contributions also feed into their future products, thereby lowering R&D costs.
The business strategy for the Arduino is that anyone can directly copy, manufacture, and sell clones, but they cannot brand them as "Arduino".
Only boards made by the company can be officially called Arduino.
"Arduino" itself is trademarked, which does not affect its open source nature.
____


== https://remodel.dk/[REMODEL toolkit]

[quote,Pen-Yuan Hsing]
____
The REMODEL toolkit that helps you uncover how to create economically sustainable open source-based business models.
This is done through seven phases of hands-on design exercises and practical experimentation.
The toolkit is licensed under CC BY-SA and has been successfully used by multiple real-life businesses.
____


== Honorable mentions

The following case studies are honorable mentions.
They are honorable mentions because they either partially implement Open Hardware design or methodologies, but fall short in other ways.

=== https://ultimatehackingkeyboard.com/[Ultimate Hacking Keyboard]

Consumer-focused hardware.
Source code is available online, but it is released under custom proprietary licenses.
The custom licenses violate the https://fsfe.org/freesoftware/[Four Freedoms] of Free Software:
specifically, the freedom to use.
However, it is still an interesting project, so it is included here as a reference.

Here is what one of our contributors had to say about it:

____
They bootstrapped their business by starting small.
They also had a successful round of crowdfunding.
To know my knowledge, this company is now self-sufficient (or close to), and their keyboards get amazing reviews.
Because hardware and firmware are [public], users create custom modifications and extensions that end essentially provide free advertising.
____
