---
title: Fedora Project
description: The Fedora Project is a community of people working together to build a free and open source operating system.
tags: ["linux"]
categories: "communities"
downloadBtn: "true"

---
:toc:

[link=https://creativecommons.org/licenses/by-sa/4.0/]
image::https://img.shields.io/badge/License-CC%20BY--SA%204.0-lightgrey.svg[License: CC BY-SA 4.0]

"Fedora" is not only a kind of hat, but also a large Open Source community with a unique role in the Open Source ecosystem.
This page provides an overview of the Fedora Linux distribution, project, and community.


[[about]]
== What is Fedora?

Fedora is three different things, rolled into one.

[[linux]]
=== Linux kernel distribution

*Fedora is a Linux kernel distribution*.
The Linux kernel is just one part of a computer system.
To make Linux useful, you need to combine it with other software and an interface that someone can use for a purpose.
Fedora is a Linux distribution, just like many others (Debian, Ubuntu, Arch Linux, CentOS/RHEL, etc.).

[[project]]
=== Project

*Fedora is a project*.
Fedora provides a Free and Open Source software platform for innovative technology.
New technologies can be explored and tested in ways that few other projects can offer.
This way, Fedora becomes a platform for collaboration on user-focused solutions built on that platform.
Successful implementations of technology in Fedora often result in wide-spread adoption through downstream projects, like Red Hat Enterprise Linux (RHEL), CentOS, and many other Linux distributions.

The one-liner often used to describe Fedora is below:

[quote, Fedora's Mission and Foundations]
____
In plain English, we make an operating system and we make it easy for you do useful stuff with it.
____

[[community]]
=== Community

*Fedora is a community*.
Not just any community, but a global community spanning multiple continents.
Fedora places strong value in its community.
Fedora contributors are not just contributors, but people with their own lives and stories.
People involved with Fedora tend to be passionate about what they do and the people they collaborate with.


[[background]]
== Background

For additional background about the Fedora Project, see https://en.wikipedia.org/wiki/The_Fedora_Project[its Wikipedia page].

[quote, Wikipedia contributors, CC BY-SA 3.0]
____
The Fedora Project is an independent project to co-ordinate the development of https://en.wikipedia.org/wiki/Fedora_Linux[Fedora Linux], a https://en.wikipedia.org/wiki/Linux_kernel[Linux kernel]-based operating system, operating with the vision of "a world where everyone benefits from free and open source software built by inclusive, welcoming, and open-minded communities."
The project's mission statement is to create "an innovative platform for hardware, clouds, and containers that enables software developers and community members to build tailored solutions for their users".
The project also oversees Extra Packages for Enterprise Linux, a special interest group which maintains the eponymous packages.
The project was founded in 2003 as a result of a merger between the https://en.wikipedia.org/wiki/Red_Hat_Linux[Red Hat Linux] (RHL) and Fedora Linux projects.
It is sponsored by https://en.wikipedia.org/wiki/Red_Hat[Red Hat] primarily, but its employees make up only 35% of project contributors, and most of the over 2,000 contributors are unaffiliated members of the community.
____


[[participate]]
== Get involved with Fedora

Fedora has a team of people to help newcomers get involved with Fedora, known as the https://docs.fedoraproject.org/en-US/fedora-join/[Fedora Join Special Interest Group].
This is the best way to explore participation in Fedora and see what options there are out there.

If you are a UNICEF Innovation Fund company, reach out to your Open Source Mentor for extra guidance in an Open Source check-in call.
