---
title: Public Lab
description: Public Lab is a community and a non-profit, democratizing science to address environmental issues that affect people.
tags: ["citizen science", "environment"]
categories: "communities"
downloadBtn: "true"

---

[link=https://creativecommons.org/licenses/by-sa/4.0/]
image::https://img.shields.io/badge/License-CC%20BY--SA%204.0-lightgrey.svg[License: CC BY-SA 4.0]

Public Lab is a community of practice that has informally collaborated with UNICEF Innovation Fund team members in the past.
To learn more about this community, reach out to your assigned Open Source Mentor or see the contact info below.


== About Public Lab

[quote, Public Lab contributors, CC BY-SA 2020]
____
Access to knowledge is a fundamental right.
When people want to investigate their environment, Public Lab is the place to go to find and share knowledge, equipment, and community.

We’re rooted in the belief that the best ideas and solutions come from collaborations between on-the-ground communities with deep knowledge of local issues in close, equitable, and sustainable partnerships with networks that bring skills, capacity, science, and technology to bear.

We raise awareness about health impacts, improve scientific agency, build new scientific and technological skills, and mitigate certain exposures.
When people can easily and reliably track local effects associated with environmental injustices — increased flooding, poor air quality, pollution and destruction of wetlands — they can make better-informed decisions and take action.
____


== Contact Public Lab

The best way to get in touch is by emailing the team at staff `at` publiclab.org.
If you are trying to reach a particular staff member, please visit the https://publiclab.org/wiki/plots-staff[Public Lab Nonprofit Staff] page.

Useful links:

* https://github.com/publiclab[GitHub]
** https://github.com/publiclab/plots2[plots2]:
   a collaborative knowledge-exchange platform in Rails
* https://app.element.io/#/room/#publiclab:matrix.org[Element/Matrix chat room] (`#publiclab:matrix.org`)
* https://gitter.im/publiclab/publiclab[Gitter chat room] (bridged together with Element room)
