---
title: "GPLv2 vs. GPLv3"
weight: 30

---
*The information shared on this page does not constitute legal or financial advice*.

This page provides an interpretation of the key differences between v2 and v3 of the GNU Public License, or G.P.L.
The key differences are summarized in each section below.

:toc:


[[tivoization]]
== Why update? Stallman's objection to Tivoization

In the early 2000s, American corporation TiVo Inc. was criticized by the Free Software community for their popular digital video recorder (DVR) product.
Free Software activist https://en.wikipedia.org/wiki/Richard_Stallman[Richard M. Stallman] criticized how TiVo violated the spirit of Free Software by placing software restrictions on their hardware products.

The TiVo projects relied on the popular Open Source https://en.wikipedia.org/wiki/Linux[Linux] platform.
Because Linux used the GNU General Public License version 2 (GPLv2), TiVo was required to distribute source code for anyone who receives the software.
Stallman asserted TiVo circumventing this goal by blocking users from running modified software on its hardware by design.
TiVo products would only run programs whose digital signature matched those authorized by TiVo.

This loophole was controversial.
In 2006, the https://en.wikipedia.org/wiki/Free_Software_Foundation[Free Software Foundation] would respond with a new version of the GNU Public License, version 3.
It included language to avoid this loophole, which commonly became known as https://en.wikipedia.org/wiki/Tivoization[Tivoization].

[[tivoization-opinions]]
=== Other opinions

Not everyone agreed to the added language to the GPLv3.
One of the largest projects to adopt the GPLv2, Linux, chose not to upgrade the license.
Linus Torvalds, the lead developer of Linux, asserts that the https://www.youtube.com/watch?v=PaKIZ7gJlRU[GPLv3 goes against what the GPLv2 means] for him as a software developer:

{{< youtube PaKIZ7gJlRU >}}


[[anti-circumvention]]
== Anti-Circumvention Law

In section 3, the GPL offers protections for user rights from anti-circumvention law.
This makes an interesting external reference to https://en.wikisource.org/wiki/WIPO_Copyright_Treaty#Article_11._Obligations_concerning_Technological_Measures[article 11] of the https://en.wikipedia.org/wiki/WIPO_Copyright_Treaty[WIPO Copyright Treaty] signed on 20 December 1996.
It appears to make clear provisions that waive legal power to forbid circumvention of the GPLv3-covered work.
It makes this requirement in the context of the WIPO Copyright Treaty to strengthen its appeal.


[[user-product-rules]]
== User Product rules

The https://www.gnu.org/licenses/gpl-faq.html#Tivoization [GPL Frequently Asked Questions page] explains this well:

[quote,GPL Frequently Asked Questions]
____
Some devices utilize free software that can be upgraded, but are designed so that users are not allowed to modify that software.
There are lots of different ways to do this;
for example, sometimes the hardware checksums the software that is installed, and shuts down if it doesn't match an expected signature.
The manufacturers comply with GPLv2 by giving you the source code, but you still don't have the freedom to modify the software you're using.
We call this practice tivoization.

When people distribute User Products that include software under GPLv3, section 6 requires that they provide you with information necessary to modify that software.
User Products is a term specially defined in the license;
examples of User Products include portable music players, digital video recorders, and home security systems.
____


[[cure-period]]
== Cure period and the GPL Cooperation Commitment

The GPLv3 includes an explicit cure period.
A cure period is like a grace period to fix a violation of the License.
Violators have 30 days after notification of noncompliance to "reinstate" their License by fixing the violation.
If the violation is cured in the cure period, there is no harm, no foul.

Technically, with the GPLv2, an actor may choose to immediately pursue legal action for noncompliance with the terms of the GPLv2.
This led to the creation of the https://gplcc.github.io/gplcc/[*GPL Cooperation Commitment*], driven by Red Hat.
In order to address this imbalance in GPLv2 license enforcement, Red Hat, IBM, Google, and Facebook announced the GPL Cooperation Commitment in November 2017 to apply the GPLv3 cure provisions for their GPLv2 and LGPLv2.x licensed software.


[[legalese]]
== "Legalese"

The GPLv3 is nearly double the length of the GPLv2 (5,644 words vs. 2,971 words).
The GPLv3 reads more like a legal document than the GPLv2.
That said, there is a lot more "legal speak" in version 3 than its predecessor.
This works to the advantage of Software Freedom by using more concrete and defined language to spell out how the GPL was commonly applied and understood before 2007.

Most of these changes are minor or trivial, and so are not explained here.
One example of this is in section 9, "Acceptance Not Required for Having Copies."
Unlike the GPLv2, version 3 better defines that you indicate acceptance of the License by modifying or propagating a GPLv3-covered work.
